### ISSUE TITLE
Problems with package name.

### ISSUE THREAD

**Issue by eliotb** [mjuenema/python-TSIP#2]
I don't think a dash '-' is valid in a module name.
I.e. 'python-TSIP' is not valid.

As the package is pure python, I'd drop the 'python-' prefix.
And taking a lead from python3, make the module name lower case.

so:  the module name will be 'tsip'

**Comment by mjuenema** [comment]
I guess 'tsip' it is then :-)

**Comment by eliotb** [comment]
Thanks.  I didn't presume to make that decision for you. (No problem with keeping this github repo named as 'python-TSIP' though)

Apart from these little issues, your project has already saved me a lot of work! 
So thank you for making it.  

I am working with an extension to TSIP (AFAIK docs not publicly available), and it has been very easy to add support for some custom packet types.  I'll have to check about whether I can contribute this back when I'm finished, or if the vendor doesn't want them made public.

**Comment by mjuenema** [comment]
It's all fine with me. That's the beauty of a library/framework. 

Good night across the Tasman Sea.
