### ISSUE TITLE
Problems running setup.py

### ISSUE THREAD

**Issue by eliotb** [mjuenema/python-TSIP#3]
$ ./setup.py build
      File "./setup.py", line 13
    from python-TSIP.config import NAME, VERSION, LICENSE
               ^
    SyntaxError: invalid syntax

python-TSIP.config is missing from repo, plus name problem as raised in previous issue.
(I just put in some dummy values, and replaced 'python-TSIP' with 'tsip' everywhere to allow me to continue...)

    $ ./setup.py build
    Traceback (most recent call last):
      File "./setup.py", line 15, in <module>
    readme = open(join(dirname(__file__), 'README.rst')).read()
    IOError: [Errno 2] No such file or directory: './README.rst'

    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.rst'

Replaced  README.rst with README.md in setup.py and MANIFEST.in

**Comment by eliotb** [comment]
Oops, I didn't see the 'develop' branch, so please ignore the comment about README.rst
The rest still applies I think?

**Comment by mjuenema** [comment]
Thanks for identifying the problem. The ugly truth is, lots of things are not working yet. There are a couple of loose bits and pieces for which I am struggling to find the time to fix them. It always comes as a bit of a shock when someone actually comments on my code ;-) On the other hand it encourages me to work on it...

I follow the "git flow" (https://github.com/nvie/gitflow) model so all development happens in the 'develop' or 'feature/*' branches.

**Comment by mjuenema** [comment]
This particular problem with setup.py is fixed. I need to write test cases for setup.py targets.
